/**
 * UDLA CheckIn
 * Web API para registro de tiempos para docentes
 *
 * OpenAPI spec version: v1
 * Contact: jose.escudero@udla.edu.ec
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface FacultyDto {
    id?: number;
    name: string;
}
